version: "2"

services:
    redis:
        image: redis
        command: ["sh", "-c", "exec redis-server"]
        networks:
            - backend
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        depends_on:
            - redis
        ports:
            - 8080:8000
        networks:
            - backend
            - frontend
        volumes:
            - ./:/mnt
        command: ["sh","-c","/usr/local/imagecup/dist/Debug/GNU-Linux/cpp"]

networks:
  frontend:
  backend:

