version: "2"

services:
    redis:
        image: redis
        command: ["sh", "-c", "exec redis-server"]
        networks:
            - backend
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        depends_on:
            - redis
        ports:
            - 8080:8000
#            - 4848:4848
        networks:
            - backend
            - frontend
        volumes:
            - ./:/mnt
            - ./images.full:/usr/local/glassfish4/glassfish/domains/domain1/applications/ImageUpload_-_Java/images.full
            - ./images.thumb:/usr/local/glassfish4/glassfish/domains/domain1/applications/ImageUpload_-_Java/images.thumb

networks:
  frontend:
  backend:

