version: '2'

services:
    apache-web:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: apache-web
        ports:
            - 8080:80
        volumes:
            - ./:/var/www
            - ./src:/var/www/html
    redis:
        image: redis
        command: ["sh", "-c", "exec redis-server"]

